export const copy = {
  en: {
    skip: 'Skip to content', navWork: 'The work', navAbout: 'The person', navContact: 'Let’s talk', menu: 'Open navigation', closeMenu: 'Close navigation',
    available: 'Open for a good project', role: 'Independent developer', location: 'Working everywhere, from here.',
    hero1: 'A developer.', hero2: 'With a twist.',
    intro: 'I’m Max. I build websites and Telegram bots for people who care how things look and how they work.',
    viewWork: 'Explore what I build', heroNote: 'A bit of curiosity. A lot of code.', scroll: 'There’s more down here', sculpture: 'Drag to give it a spin',
    ribbon: ['Built from scratch', 'Not from a template', 'A little unexpected', 'Very much intentional'],
    workLabel: 'Ideas, made tangible', workTitle: 'Less explaining.\nMore showing.', workIntro: 'A few self-initiated concepts. Different personalities, same attention to the details.',
    concept: 'Interactive concept', projectAction: 'Take a closer look',
    formaTag: 'Website / Design & development', formaDesc: 'A quiet home for bold architecture. Room to breathe, down to the last pixel.',
    relayTag: 'Telegram bot / Automation', relayDesc: 'Bookings without the back-and-forth. Pick a day, grab a slot, get on with yours.',
    servicesLabel: 'What I can help with', servicesTitle: 'Looks right.\nWorks even better.',
    services: [
      { title: 'Websites with a point of view.', text: 'A landing page, a company website, an online store. Built around your business, not squeezed into a template.', tags: ['Design', 'Development', 'Mobile-first'] },
      { title: 'Bots that do the boring part.', text: 'Bookings, payments, notifications, orders. Your customers stay in Telegram. You get a little more of your day back.', tags: ['Telegram bots', 'Integrations', 'Automation'] },
      { title: 'The part after “it’s live”.', text: 'A launch isn’t a goodbye. I can help with updates, new features, and the things you only notice once people start using it.', tags: ['Support', 'Improvements', 'New features'] },
    ],
    aboutLabel: 'The person behind the pixels', aboutTitle: 'Hey, I’m Max.',
    aboutText: 'I like the space where design meets code. A button that feels just right. A page that makes you stop for a second. A bot that saves you twenty messages.',
    aboutText2: 'You talk to me, I build it. No passing your idea down a chain of people. We figure out what matters, make it, and get it out into the world.',
    aboutNote: 'Small details. Big difference.', aboutSticker: 'Human behind\nthe code',
    processLabel: 'No mystery in the process', processTitle: 'From “hello”\nto “look at that”.', process: [
      { title: 'Tell me the idea.', text: 'A rough sketch or a three-line message is enough. We’ll work out the scope, timing, and price before starting.' },
      { title: 'Watch it take shape.', text: 'You see the design and working versions along the way. Feedback happens early, not the night before launch.' },
      { title: 'Let’s put it out there.', text: 'I test it, help with launch, and show you how everything works. You get the source code, too.' },
    ],
    contactLabel: 'Got something in mind?', contactTitle: 'Let’s make\nit a real thing.', contactText: 'Tell me what you’re thinking. A polished brief is very much optional.', contactCta: 'Message me on Telegram', copy: 'Copy username', copied: 'Username copied', copyFail: 'Copy @cylaro manually',
    footer: 'Designed & built by Max', backTop: 'Back to the top', footerNote: 'A little different. On purpose.',
    close: 'Close preview', demoNotice: 'A self-initiated concept, not client work.',
    formaSubtitle: 'Spaces for living.', formaBody: 'Considered spaces. Honest materials. Architecture that feels like home.', formaLink: 'Explore the spaces', formaNext: 'Next space', formaRooms: ['The hillside house', 'The courtyard house', 'The coastal retreat'],
    relayTitle: 'A booking, minus the phone call.', relayBody: 'Try this little Telegram-style demo. Choose a service and a time; the bot takes it from there.',
    botStatus: 'booking assistant', botGreeting: 'Hey! Let’s find a little time for you. What would you like to book?', botServices: ['Haircut', 'Consultation', 'Training'], botPick: 'Nice. Pick a time for tomorrow:', botConfirm: 'You’re all set. Tomorrow at', botEnd: 'This is a demo, so no real booking was made.', botReset: 'Try another booking', botSend: 'Choose an option above',
  },
  ru: {
    skip: 'К содержимому', navWork: 'Работы', navAbout: 'Обо мне', navContact: 'Обсудим?', menu: 'Открыть меню', closeMenu: 'Закрыть меню',
    available: 'Открыт к интересным проектам', role: 'Независимый разработчик', location: 'На связи, где бы вы ни были.',
    hero1: 'Разработчик.', hero2: 'С изюминкой.',
    intro: 'Я Макс. Делаю сайты и Telegram-ботов для тех, кому важно не только как работает, но и как выглядит.',
    viewWork: 'Посмотреть, что я делаю', heroNote: 'Немного любопытства. Много кода.', scroll: 'Ниже ещё интереснее', sculpture: 'Потяните, чтобы покрутить',
    ribbon: ['С чистого листа', 'Не по шаблону', 'Чуть неожиданно', 'Всё продумано'],
    workLabel: 'От идеи к результату', workTitle: 'Лучше один\nраз показать.', workIntro: 'Несколько моих концептов. У каждого свой характер, в каждом внимание к мелочам.',
    concept: 'Интерактивный концепт', projectAction: 'Посмотреть поближе',
    formaTag: 'Сайт / Дизайн и разработка', formaDesc: 'Спокойный сайт для смелой архитектуры. Много воздуха и ничего лишнего.',
    relayTag: 'Telegram-бот / Автоматизация', relayDesc: 'Запись без десяти уточняющих сообщений. Выбрать день, время и заняться своими делами.',
    servicesLabel: 'Чем могу помочь', servicesTitle: 'Красиво снаружи.\nПродумано внутри.',
    services: [
      { title: 'Сайты со своим характером.', text: 'Лендинг, сайт компании или интернет-магазин. Отталкиваюсь от вашей задачи, а не от того, что помещается в шаблон.', tags: ['Дизайн', 'Разработка', 'Адаптивность'] },
      { title: 'Боты для скучных дел.', text: 'Записи, оплата, уведомления, заказы. Клиенты остаются в Telegram, а у вас освобождается немного времени.', tags: ['Telegram-боты', 'Интеграции', 'Автоматизация'] },
      { title: 'Жизнь после запуска.', text: 'Выложить сайт не значит попрощаться. Помогу с обновлениями, новыми функциями и тем, что выяснится только после запуска.', tags: ['Поддержка', 'Доработки', 'Новые функции'] },
    ],
    aboutLabel: 'Кто за всем этим стоит', aboutTitle: 'Привет, я Макс.',
    aboutText: 'Мне нравится, когда дизайн и код работают вместе. Кнопка, которую приятно нажать. Страница, на которой хочется задержаться. Бот, который экономит двадцать сообщений.',
    aboutText2: 'Вы общаетесь со мной, я же всё и делаю. Не передаю задачу по цепочке. Разбираемся, что важно, собираем и запускаем.',
    aboutNote: 'Мелочи решают.', aboutSticker: 'За кодом\nчеловек',
    processLabel: 'Без загадок и сюрпризов', processTitle: 'От «привет»\nдо «смотрите, как вышло».', process: [
      { title: 'Расскажите идею.', text: 'Наброска или пары сообщений достаточно. До начала договоримся об объёме, сроках и цене.' },
      { title: 'Смотрите, как получается.', text: 'Показываю дизайн и рабочие версии по ходу дела. Обсуждаем правки заранее, а не за ночь до запуска.' },
      { title: 'Пора выпускать.', text: 'Проверяю, помогаю с запуском и объясняю, как всё устроено. Исходный код тоже отдаю вам.' },
    ],
    contactLabel: 'Есть одна идея?', contactTitle: 'Давайте\nеё сделаем.', contactText: 'Напишите, что задумали. Идеальное техническое задание необязательно.', contactCta: 'Написать в Telegram', copy: 'Скопировать ник', copied: 'Ник скопирован', copyFail: 'Скопируйте @cylaro вручную',
    footer: 'Дизайн и код: Макс', backTop: 'Наверх', footerNote: 'Не как у всех. Так задумано.',
    close: 'Закрыть просмотр', demoNotice: 'Авторский концепт, не клиентский проект.',
    formaSubtitle: 'Место для жизни.', formaBody: 'Продуманные пространства. Честные материалы. Архитектура, в которой хочется жить.', formaLink: 'Посмотреть пространства', formaNext: 'Следующий дом', formaRooms: ['Дом на холме', 'Дом с внутренним двором', 'Дом у побережья'],
    relayTitle: 'Запись без звонков.', relayBody: 'Попробуйте демо в стиле Telegram. Выберите услугу и время, остальное сделает бот.',
    botStatus: 'помощник по записи', botGreeting: 'Привет! Давайте найдём время для вас. На что хотите записаться?', botServices: ['Стрижка', 'Консультация', 'Тренировка'], botPick: 'Отлично. Выберите время на завтра:', botConfirm: 'Готово! Завтра в', botEnd: 'Это демо, настоящая запись не создана.', botReset: 'Попробовать ещё раз', botSend: 'Выберите вариант выше',
  },
};
